In [4]:
b=10
for a in range(b):
     print('hello world')

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world


In [19]:
def avg(x,y):
    print("first input is ", x)
    print("second input is ", y)
    a=(x+y)/2
    print("average is ", a)
    return a


In [18]:
avg(1,2)

first input is  1
second input is  2
average is  1.5


In [20]:
c=avg(1,6)

first input is  1
second input is  6
average is  3.5


In [21]:
c

3.5

In [16]:
c

In [17]:
print(c)

None


In [22]:
import numpy

In [23]:
a= numpy.zeros([3,2])

In [25]:
print (a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [52]:
numpy.random.normal(0,0.1,(3,2)) 
                    #0.1 표준편차, 3,2 3행 2열
    

array([[ 0.01370052,  0.12200425],
       [-0.06788517, -0.01623082],
       [ 0.09332292,  0.00375127]])

In [53]:
list_a = [3,2]
b = numpy.array(list_a)

In [54]:
list_a

[3, 2]

In [55]:
b

array([3, 2])

In [56]:
a=numpy.array([1,2,3])
b=numpy.array([10,100,1000])
c = a+b

In [57]:
c

array([  11,  102, 1003])

In [58]:
a

array([1, 2, 3])

In [59]:
a+=a

In [60]:
a

array([2, 4, 6])

AttributeError: 'numpy.ndarray' object has no attribute 'append'