In [12]:
import numpy as np

a15=np.array([1,2,3,4])
a16=np.array([1,2,3,4], ndmin=2) #2차원으로 선언
print(a15)
print(a15.T)
print(a16)
print(a16.T)
print(a15.shape)

[1 2 3 4]
[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(4,)


In [16]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
array3 = array1+array2
print(array3)

print(array1 >= 3)
print(array2 < 6)

idx_list = array1>=3
array4 = array1[idx_list]
print(array4)

[ 6  8 10 12]
[False False  True  True]
[ True False False False]
[3 4]


In [2]:
print("-"*20)

--------------------


In [3]:
print ("{0} {0} Science {1}".format("Computer", "2012"))

Computer Computer Science 2012


In [11]:
list = [i*i for i in range (10) if i%2==0]
print(list)

[0, 4, 16, 36, 64]
